name: boolean
description: Extension functions on strings and numbers to convert them to bools.
version: 2.0.0-nullsafety.0
repository: https://github.com/mjstel/boolean

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3 
  test: ^1.16.0-nullsafety.16  
