name: boolean
description: Utility functions to convert strings and numbers to bools.
version: 1.0.0
repository: https://github.com/mjstel/boolean

environment:
  sdk: ">=2.10.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
